---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-poc
spec:
  selector:
    matchLabels:
      app: redis-poc
  replicas: 10
  template:
    metadata:
      labels:
        app: redis-poc
    spec:
      containers:
        - name: redis-poc
          image: redis-poc:latest
          ports:
            - containerPort: 8080
#          env:   # Setting Environmental Variables
#            - name: DB_HOST   # Setting Database host address
#              value: mysql
#            - name: DB_NAME  # Setting Database name
#              value: fleetdb
#            - name: DB_USERNAME  # Setting Database username
#              value: root
#            - name: DB_PASSWORD # Setting Database password
#              value: root
# This seperator --- below is MANDATORY!!!
---
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: redis-poc
spec:
  ports:
    - protocol: "TCP"
      port: 8080    # Port inside the cluster
      targetPort: 8080   # Port exposed to the outside
  selector:
    app: redis-poc
  type: NodePort