apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-poc
  template:
    metadata:
      labels:
        app: redis-poc
    spec:
      containers:
        - name: redis-poc
          image: redis-poc:1.0.0
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
            - name: multicast
              protocol: TCP
              containerPort: 5701
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 30
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "redis,kubernetes"
            - name: parameters.initialCount
              value: "1000000"

---

apiVersion: v1
kind: Service
metadata:
  name: redis-poc
spec:
  type: NodePort
  selector:
    app: redis-poc
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      nodePort: 30100
    - port: 5701
      name: multicast
      targetPort: 5701